### ISSUE TITLE
Any interval list for hg38 in mutect2 workflow ?

### ISSUE THREAD

**Issue by woodword** [gatk-workflows/gatk4-somatic-snvs-indels#10]
I tried to repeat mutect2 workflow. But a hg19 interval list is used in mutect2.exome.inputs.json "Mutect2.intervals" option. 
I'm wondering if there's any interval list available for hg38 genome

**Comment by bshifaw** [comment]
Hi @woodword 

Not that I know of, but keep in mind the hg19 intervals are example files. Intervals are generally produced by the user based on the ["capture targets used for the library prep, and is typically provided by the prep kit manufacturer"](https://gatkforums.broadinstitute.org/gatk/discussion/comment/46329#Comment_46329). 

For any more questions please don't hesitate to reach us on the [GATK forum](https://gatkforums.broadinstitute.org/gatk/categories/ask-the-team).
