### ISSUE TITLE
PAPI error code 5. Message: 10: Failed to delocalize files

### ISSUE THREAD

**Issue by wynstep** [gatk-workflows/gatk4-somatic-snvs-indels#11]
When I try to run the "mutect2_pon" wdl from FireCloud, I receive this error (and many others of the same type):

```Task Mutect2.M2:6:1 failed. Job exit code 1. Check gs://fc-934217d7-12c3-47b0-ae3a-e69c00b6abd9/6cb35dfc-72e3-434e-ab01-c76ea6b0692c/Mutect2_Panel/70fae733-118f-4f50-925c-56143a7124c0/call-Mutect2/shard-0/Mutect2/8d5cc5f9-4224-446d-b5de-b6289b75bc78/call-M2/shard-6/stderr for more information. PAPI error code 5. 10: Failed to delocalize files: failed to copy the following files: "/mnt/local-disk/output.vcf -> gs://fc-934217d7-12c3-47b0-ae3a-e69c00b6abd9/6cb35dfc-72e3-434e-ab01-c76ea6b0692c/Mutect2_Panel/70fae733-118f-4f50-925c-56143a7124c0/call-Mutect2/shard-0/Mutect2/8d5cc5f9-4224-446d-b5de-b6289b75bc78/call-M2/shard-6/output.vcf (cp failed: gsutil -q -m cp -L /var/log/google-genomics/out.log /mnt/local-disk/output.vcf gs://fc-934217d7-12c3-47b0-ae3a-e69c00b6abd9/6cb35dfc-72e3-434e-ab01-c76ea6b0692c/Mutect2_Panel/70fae733-118f-4f50-925c-56143a7124c0/call-Mutect2/shard-0/Mutect2/8d5cc5f9-4224-446d-b5de-b6289b75bc78/call-M2/shard-6/output.vcf, command failed: CommandException: No URLs matched: /mnt/local-disk/output.vcf\nCommandException: 1 file/object could not be transferred.\n); /mnt/local-disk/tumor_name.txt -> gs://fc-934217d7-12c3-47b0-ae3a-e69c00b6abd9/6cb35dfc-72e3-434e-ab01-c76ea6b0692c/Mutect2_Panel/70fae733-118f-4f50-925c-56143a7124c0/call-Mutect2/shard-0/Mutect2/8d5cc5f9-4224-446d-b5de-b6289b75bc78/call-M2/shard-6/tumor_name.txt (cp failed: gsutil -q -m cp -L /var/log/google-genomics/out.log /mnt/local-disk/tumor_name.txt gs://fc-934217d7-12c3-47b0-ae3a-e69c00b6abd9/6cb35dfc-72e3-434e-ab01-c76ea6b0692c/Mutect2_Panel/70fae733-118f-4f50-925c-56143a7124c0/call-Mutect2/shard-0/Mutect2/8d5cc5f9-4224-446d-b5de-b6289b75bc78/call-M2/shard-6/tumor_name.txt, command failed: CommandException: No URLs matched: /mnt/local-disk/tumor_name.txt\nCommandException: 1 file/object could not be transferred.\n); /mnt/local-disk/output.vcf.idx -> gs://fc-934217d7-12c3-47b0-ae3a-e69c00b6abd9/6cb35dfc-72e3-434e-ab01-c76ea6b0692c/Mutect2_Panel/70fae733-118f-4f50-925c-56143a7124c0/call-Mutect2/shard-0/Mutect2/8d5cc5f9-4224-446d-b5de-b6289b75bc78/call-M2/shard-6/output.vcf.idx (cp failed: gsutil -q -m cp -L /var/log/google-genomics/out.log /mnt/local-disk/output.vcf.idx gs://fc-934217d7-12c3-47b0-ae3a-e69c00b6abd9/6cb35dfc-72e3-434e-ab01-c76ea6b0692c/Mutect2_Panel/70fae733-118f-4f50-925c-56143a7124c0/call-Mutect2/shard-0/Mutect2/8d5cc5f9-4224-446d-b5de-b6289b75bc78/call-M2/shard-6/output.vcf.idx, command failed: CommandException: No URLs matched: /mnt/local-disk/output.vcf.idx\nCommandException: 1 file/object could not be transferred.\n```

Could you please help me in understanding what's the issue? Thanks

**Comment by bshifaw** [comment]
Hi @wynstep 

Please post questions to the [GATK Forum](https://gatkforums.broadinstitute.org/gatk/categories/ask-the-team). If you're running this on Firecloud please post it on the [Firecloud Forum](https://gatkforums.broadinstitute.org/firecloud/categories/ask-the-firecloud-team)
