### ISSUE TITLE
Wrong inputs in mutect2_pon.inputs.json template

### ISSUE THREAD

**Issue by kaboroevich** [gatk-workflows/gatk4-somatic-snvs-indels#23]
Hello,

Currently the input section of [mutect2_pon.inputs.json](https://github.com/gatk-workflows/gatk4-somatic-snvs-indels/blob/master/mutect2_pon.inputs.json) reads:

    "##_COMMENT1": "Inputs",     
    "Mutect2_Panel.normal_reads": "Array[File]",     
    "Mutect2_Panel.normal_reads_index": "Array[File]",     
    "Mutect2_Panel.pon_name": "String",     
    "#Mutect2_Panel.Mutect2.normal_bam": "(optional) File?",     
    "#Mutect2_Panel.Mutect2.normal_bai": "(optional) File?",

But when I run the workflow, I get missing required inputs. I believe the correct template should be:

    "##_COMMENT1": "Inputs",
    "Mutect2_Panel.normal_bams": "Array[File]",
    "Mutect2_Panel.normal_bais": "Array[File]",
    "Mutect2_Panel.pon_name": "String",
    "Mutect2_Panel.gnomad": "gs://gatk-best-practices/somatic-b37/af-only-gnomad.raw.sites.vcf"

I am running this without docker, but I don't believe that would have caused the issue.

**Comment by bshifaw** [comment]
Thanks for catching this, I'll work on fix it.
